# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml 
name: nf-core-circrnasponging
channels:
  - conda-forge
  - defaults
  - anaconda
  - bioconda
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _r-mutex=1.0.1=anacondar_1
  - async_generator=1.10=py_0
  - attrs=21.4.0=pyhd8ed1ab_0
  - beautifulsoup4=4.11.1=pyha770c72_0
  - pyliftover=0.4=py_0
  - binutils_impl_linux-64=2.36.1=h193b22a_2
  - binutils_linux-64=2.36=hf3e587d_9
  - bioconductor-annotate=1.72.0=r41hdfd78af_0
  - bioconductor-annotationdbi=1.56.1=r41hdfd78af_0
  - bioconductor-annotationfilter=1.18.0=r41hdfd78af_0
  - bioconductor-biobase=2.54.0=r41h5c21468_1
  - bioconductor-biocfilecache=2.2.0=r41hdfd78af_0
  - bioconductor-biocgenerics=0.40.0=r41hdfd78af_0
  - bioconductor-biocio=1.4.0=r41hdfd78af_0
  - bioconductor-biocparallel=1.28.3=r41h619a076_0
  - bioconductor-biomart=2.50.0=r41hdfd78af_0
  - bioconductor-biostrings=2.62.0=r41h5c21468_1
  - bioconductor-bsgenome=1.62.0=r41hdfd78af_0
  - bioconductor-delayedarray=0.20.0=r41h5c21468_1
  - bioconductor-deseq2=1.34.0=r41h619a076_1
  - bioconductor-enhancedvolcano=1.12.0=r41hdfd78af_0
  - bioconductor-ensembldb=2.18.1=r41hdfd78af_0
  - bioconductor-genefilter=1.76.0=r41ha086028_1
  - bioconductor-geneplotter=1.72.0=r41hdfd78af_0
  - bioconductor-genomeinfodb=1.30.0=r41hdfd78af_0
  - bioconductor-genomeinfodbdata=1.2.7=r41hdfd78af_1
  - bioconductor-genomicalignments=1.30.0=r41h5c21468_1
  - bioconductor-genomicfeatures=1.46.1=r41hdfd78af_0
  - bioconductor-genomicranges=1.46.1=r41h5c21468_0
  - bioconductor-graph=1.72.0=r41h5c21468_1
  - bioconductor-iranges=2.28.0=r41h5c21468_1
  - bioconductor-keggrest=1.34.0=r41hdfd78af_0
  - bioconductor-matrixgenerics=1.6.0=r41hdfd78af_0
  - bioconductor-protgenerics=1.26.0=r41hdfd78af_0
  - bioconductor-rbgl=1.70.0=r41h619a076_1
  - bioconductor-rgraphviz=2.38.0=r41h619a076_1
  - bioconductor-rhtslib=1.26.0=r41h5c21468_1
  - bioconductor-rsamtools=2.10.0=r41h619a076_1
  - bioconductor-rtracklayer=1.54.0=r41hdc01c10_2
  - bioconductor-s4vectors=0.32.3=r41h5c21468_0
  # - bioconductor-sponge=1.16.0=r41hdfd78af_0
  - bioconductor-summarizedexperiment=1.24.0=r41hdfd78af_0
  - bioconductor-tximport=1.22.0=r41hdfd78af_0
  - bioconductor-xvector=0.34.0=r41h5c21468_1
  - bioconductor-zlibbioc=1.40.0=r41h5c21468_1
  - bowtie=1.3.1=py39hd400a0c_1
  - brotlipy=0.7.0=py39hb9d737c_1004
  - bwa=0.7.17=h7132678_9
  - bwidget=1.9.14=ha770c72_1
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.18.1=h7f98852_0
  - ca-certificates=2021.10.8=ha878542_0
  - cairo=1.16.0=ha61ee94_1011
  - certifi=2021.10.8=py39hf3d152e_2
  - cffi=1.15.0=py39h4bc2ebd_0
  - cryptography=36.0.2=py39hd97740a_1
  - curl=7.83.0=h7bff187_0
  - expat=2.4.8=h27087fc_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.0=h8e229c2_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.10.4=h0708190_1
  - fribidi=1.0.10=h36c2ea0_0
  - gcc_impl_linux-64=10.3.0=hf2f2afa_16
  - gcc_linux-64=10.3.0=hc39de41_9
  - gettext=0.19.8.1=h73d1719_1008
  - gfortran_impl_linux-64=10.3.0=h73f4979_16
  - gfortran_linux-64=10.3.0=hb09a455_9
  - gmp=6.2.1=h58526e2_0
  - graphite2=1.3.13=h58526e2_1001
  - gsl=2.7=he838d99_0
  - gxx_impl_linux-64=10.3.0=hf2f2afa_16
  - gxx_linux-64=10.3.0=h2593f52_9
  - h11=0.13.0=pyhd8ed1ab_0
  - harfbuzz=4.2.1=hf9f4e7c_0
  - icu=70.1=h27087fc_0
  - idna=3.3=pyhd8ed1ab_0
  - jbig=2.1=h7f98852_2003
  - joblib=1.1.0=pyhd8ed1ab_0
  - jpeg=9e=h166bdaf_1
  - kernel-headers_linux-64=2.6.32=he073ed8_15
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.19.3=h3790be6_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - lerc=3.0=h9c3ff4c_0
  - libblas=3.9.0=14_linux64_openblas
  - libcblas=3.9.0=14_linux64_openblas
  - libcurl=7.83.0=h7bff187_0
  - libdeflate=1.10=h7f98852_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libffi=3.4.2=h7f98852_5
  - libgcc-devel_linux-64=10.3.0=he6cfe16_16
  - libgcc-ng=11.2.0=h1d223b6_16
  - libgfortran-ng=11.2.0=h69a702a_16
  - libgfortran5=11.2.0=h5c6108e_16
  - libglib=2.70.2=h174f98d_4
  - libgomp=11.2.0=h1d223b6_16
  - libiconv=1.16=h516909a_0
  - liblapack=3.9.0=14_linux64_openblas
  - libnghttp2=1.47.0=h727a467_0
  - libnsl=2.0.0=h7f98852_0
  - libopenblas=0.3.20=pthreads_h78a6416_0
  - libpng=1.6.37=h21135ba_2
  - libsanitizer=10.3.0=h26c7422_16
  - libssh2=1.10.0=ha56f1ee_2
  - libstdcxx-devel_linux-64=10.3.0=he6cfe16_16
  - libstdcxx-ng=11.2.0=he4da1e4_16
  - libtiff=4.3.0=h542a066_3
  - libuuid=2.32.1=h7f98852_1000
  - libwebp-base=1.2.2=h7f98852_1
  - libxcb=1.13=h7f98852_1004
  - libxml2=2.9.13=h22db469_0
  - libzlib=1.2.11=h166bdaf_1014
  - lz4-c=1.9.3=h9c3ff4c_1
  - make=4.3=hd18ef5c_1
  - miranda=3.3a=hec16e2b_4
  - mirdeep2=2.0.1.3=hdfd78af_1
  - ncurses=6.3=h27087fc_1
  - numpy=1.22.3=py39hc58783e_2
  - openssl=1.1.1n=h166bdaf_0
  - outcome=1.1.0=pyhd8ed1ab_0
  - pandas=1.4.2=py39h1832856_1
  - pandoc=2.18=ha770c72_0
  - pango=1.50.7=hbd2fdc8_0
  - pcre=8.45=h9c3ff4c_0
  - pcre2=10.37=h032f7d1_0
  - perl=5.32.1=2_h7f98852_perl5
  - perl-base=2.23=pl5321hdfd78af_2
  - perl-business-isbn=3.007=pl5321hdfd78af_0
  - perl-business-isbn-data=20210112.006=pl5321hdfd78af_0
  - perl-carp=1.50=pl5321hd8ed1ab_0
  - perl-compress-raw-zlib=2.103=pl5321h87f3376_0
  - perl-constant=1.33=pl5321hd8ed1ab_0
  - perl-data-dumper=2.183=pl5321hec16e2b_1
  - perl-digest-hmac=1.04=pl5321hdfd78af_0
  - perl-digest-md5=2.58=pl5321hec16e2b_1
  - perl-encode=3.17=pl5321hec16e2b_0
  - perl-encode-locale=1.05=pl5321hdfd78af_7
  - perl-exporter=5.74=pl5321hd8ed1ab_0
  - perl-extutils-makemaker=7.64=pl5321hd8ed1ab_0
  - perl-file-listing=6.15=pl5321hdfd78af_0
  - perl-file-spec=3.48_01=pl5321hdfd78af_2
  - perl-font-ttf=1.06=pl5321hdfd78af_1
  - perl-html-parser=3.78=pl5321h9f5acd7_0
  - perl-html-tagset=3.20=pl5321hdfd78af_4
  - perl-http-cookies=6.10=pl5321hdfd78af_0
  - perl-http-daemon=6.14=pl5321hdfd78af_0
  - perl-http-date=6.05=pl5321hdfd78af_0
  - perl-http-message=6.36=pl5321hdfd78af_0
  - perl-http-negotiate=6.01=pl5321hdfd78af_4
  - perl-io-html=1.004=pl5321hdfd78af_0
  - perl-io-socket-ssl=2.074=pl5321hdfd78af_0
  - perl-io-string=1.08=pl5321hdfd78af_4
  - perl-libwww-perl=6.39=pl5321hdfd78af_1
  - perl-lwp-mediatypes=6.04=pl5321hdfd78af_1
  - perl-lwp-simple=6.39=pl5321h9ee0642_5
  - perl-mime-base64=3.16=pl5321hec16e2b_2
  - perl-net-http=6.22=pl5321hdfd78af_0
  - perl-net-ssleay=1.92=pl5321h0e0aaa8_1
  - perl-ntlm=1.09=pl5321hdfd78af_5
  - perl-parent=0.238=pl5321hd8ed1ab_0
  - perl-pdf-api2=2.043=pl5321hdfd78af_0
  - perl-socket=2.027=pl5321hec16e2b_3
  - perl-time-local=1.30=pl5321hdfd78af_0
  - perl-timedate=2.33=pl5321hdfd78af_2
  - perl-try-tiny=0.31=pl5321hdfd78af_0
  - perl-uri=5.10=pl5321hdfd78af_0
  - perl-url-encode=0.03=pl5321h9ee0642_0
  - perl-www-robotrules=6.02=pl5321hdfd78af_4
  - perl-xml-parser=2.44_01=pl5321hc3e0081_1003
  - pip=22.0.4=pyhd8ed1ab_0
  - pixman=0.40.0=h36c2ea0_0
  - proj=9.0.0=h93bde94_1
  - pthread-stubs=0.4=h36c2ea0_1001
  - pycparser=2.21=pyhd8ed1ab_0
  - pyopenssl=22.0.0=pyhd8ed1ab_0
  - pysocks=1.7.1=py39hf3d152e_5
  - python=3.9.12=h9a8a25e_1_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.9=2_cp39
  - pytz=2022.1=pyhd8ed1ab_0
  - r-ade4=1.7_19=r41h0154571_0
  - r-argparser=0.7.1=r41hc72bb7e_0
  - r-ash=1.0_15=r41h859d828_1006
  - r-askpass=1.1=r41hcfec24a_2
  - r-assertthat=0.2.1=r41hc72bb7e_2
  - r-backports=1.4.1=r41hcfec24a_0
  - r-base=4.1.3=h06d3f91_1
  - r-base64enc=0.1_3=r41hcfec24a_1004
  - r-beeswarm=0.4.0=r41hcfec24a_1
  - r-bh=1.78.0_0=r41hc72bb7e_0
  - r-bibtex=0.4.2.3=r41hcfec24a_0
  - r-biocmanager=1.30.17=r41hc72bb7e_0
  - r-bit=4.0.4=r41hcfec24a_0
  - r-bit64=4.0.5=r41hcfec24a_0
  - r-bitops=1.0_7=r41hcfec24a_0
  - r-blob=1.2.3=r41hc72bb7e_0
  - r-brio=1.1.3=r41hcfec24a_0
  - r-broom=0.8.0=r41hc72bb7e_0
  - r-bslib=0.3.1=r41hc72bb7e_0
  - r-cachem=1.0.6=r41hcfec24a_0
  - r-cairo=1.5_15=r41h06615bd_0
  - r-callr=3.7.0=r41hc72bb7e_0
  - r-cellranger=1.1.0=r41hc72bb7e_1004
  - r-cli=3.3.0=r41h7525677_0
  - r-clipr=0.8.0=r41hc72bb7e_0
  - r-codetools=0.2_18=r41hc72bb7e_0
  - r-colorspace=2.0_3=r41h06615bd_0
  - r-cpp11=0.4.2=r41hc72bb7e_0
  - r-crayon=1.5.1=r41hc72bb7e_0
  - r-crosstalk=1.2.0=r41hc72bb7e_0
  - r-curl=4.3.2=r41hcfec24a_0
  - r-data.table=1.14.2=r41hcfec24a_0
  - r-dbi=1.1.2=r41hc72bb7e_0
  - r-dbplyr=2.1.1=r41hc72bb7e_0
  - r-desc=1.4.1=r41hc72bb7e_0
  - r-diffobj=0.3.5=r41hcfec24a_0
  - r-digest=0.6.29=r41h03ef668_0
  - r-doparallel=1.0.17=r41hc72bb7e_0
  - r-dorng=1.8.2=r41hc72bb7e_1
  - r-dplyr=1.0.8=r41h7525677_0
  - r-dtplyr=1.2.1=r41hc72bb7e_0
  - r-ellipsis=0.3.2=r41hcfec24a_0
  - r-evaluate=0.15=r41hc72bb7e_0
  - r-expm=0.999_6=r41h52d45c5_0
  - r-extrafont=0.18=r41ha770c72_0
  - r-extrafontdb=1.0=r41hc72bb7e_1003
  - r-fansi=1.0.3=r41h06615bd_0
  - r-farver=2.1.0=r41h03ef668_0
  - r-fastmap=1.1.0=r41h03ef668_0
  - r-filelock=1.0.2=r41hcfec24a_1002
  - r-forcats=0.5.1=r41hc72bb7e_0
  - r-foreach=1.5.2=r41hc72bb7e_0
  - r-formatr=1.12=r41hc72bb7e_0
  - r-fs=1.5.2=r41h7525677_1
  - r-futile.logger=1.4.3=r41hc72bb7e_1003
  - r-futile.options=1.0.1=r41hc72bb7e_1002
  - r-gargle=1.2.0=r41hc72bb7e_0
  - r-generics=0.1.2=r41hc72bb7e_0
  - r-ggalt=0.4.0=r41ha770c72_2
  - r-ggbeeswarm=0.6.0=r41ha770c72_1003
  - r-ggplot2=3.3.5=r41hc72bb7e_0
  - r-ggrastr=1.0.1=r41hc72bb7e_0
  - r-ggrepel=0.9.1=r41h03ef668_0
  - r-glmnet=4.1_2=r41h859d828_0
  - r-glue=1.6.2=r41h06615bd_0
  - r-googledrive=2.0.0=r41hc72bb7e_0
  - r-googlesheets4=1.0.0=r41h785f33e_0
  - r-grbase=1.8.7=r41h930fe3c_0
  - r-gtable=0.3.0=r41hc72bb7e_3
  - r-haven=2.4.3=r41h2713e49_0
  - r-hexbin=1.28.2=r41h8da6f51_0
  - r-highr=0.9=r41hc72bb7e_0
  - r-hms=1.1.1=r41hc72bb7e_0
  - r-htmltools=0.5.2=r41h03ef668_0
  - r-htmlwidgets=1.5.4=r41hc72bb7e_0
  - r-httr=1.4.2=r41hc72bb7e_0
  - r-ids=1.0.1=r41hc72bb7e_1
  - r-igraph=1.3.1=r41hf10d5bd_0
  - r-isoband=0.2.5=r41h03ef668_0
  - r-iterators=1.0.14=r41hc72bb7e_0
  - r-jquerylib=0.1.4=r41hc72bb7e_0
  - r-jsonlite=1.8.0=r41h06615bd_0
  - r-kernsmooth=2.23_20=r41h742201e_0
  - r-knitr=1.39=r41hc72bb7e_0
  - r-labeling=0.4.2=r41hc72bb7e_1
  - r-lambda.r=1.2.4=r41hc72bb7e_1
  - r-later=1.2.0=r41h03ef668_0
  - r-lattice=0.20_45=r41hcfec24a_0
  - r-lazyeval=0.2.2=r41hcfec24a_2
  - r-lifecycle=1.0.1=r41hc72bb7e_0
  - r-locfit=1.5_9.5=r41h06615bd_0
  - r-logging=0.10_108=r41ha770c72_2
  - r-lubridate=1.8.0=r41h03ef668_0
  - r-magrittr=2.0.3=r41h06615bd_0
  - r-maps=3.4.0=r41hcfec24a_0
  - r-mass=7.3_57=r41h06615bd_0
  - r-matrix=1.4_1=r41h0154571_0
  - r-matrixstats=0.62.0=r41h06615bd_0
  - r-memoise=2.0.1=r41hc72bb7e_0
  - r-mgcv=1.8_40=r41h0154571_0
  - r-mime=0.12=r41hcfec24a_0
  - r-modelr=0.1.8=r41hc72bb7e_0
  - r-munsell=0.5.0=r41hc72bb7e_1004
  - r-nlme=3.1_157=r41h8da6f51_0
  - r-openssl=2.0.0=r41hfaab4ff_0
  - r-pheatmap=1.0.12=r41hc72bb7e_2
  - r-pillar=1.7.0=r41hc72bb7e_0
  - r-pixmap=0.4_12=r41hc72bb7e_0
  - r-pkgconfig=2.0.3=r41hc72bb7e_1
  - r-pkgload=1.2.4=r41h03ef668_0
  - r-pkgmaker=0.32.2=r41hc72bb7e_0
  - r-plogr=0.2.0=r41hc72bb7e_1003
  - r-plotly=4.10.0=r41hc72bb7e_0
  - r-plyr=1.8.7=r41h7525677_0
  - r-png=0.1_7=r41hcfec24a_1004
  - r-ppcor=1.1=r41ha770c72_1003
  - r-praise=1.0.0=r41hc72bb7e_1005
  - r-prettyunits=1.1.1=r41hc72bb7e_1
  - r-processx=3.5.3=r41h06615bd_0
  - r-progress=1.2.2=r41hc72bb7e_2
  - r-proj4=1.0_11=r41h88bfbc4_1
  - r-promises=1.2.0.1=r41h03ef668_0
  - r-ps=1.7.0=r41h06615bd_0
  - r-purrr=0.3.4=r41hcfec24a_1
  - r-r6=2.5.1=r41hc72bb7e_0
  - r-ragg=1.2.2=r41hc1f6985_0
  - r-rappdirs=0.3.3=r41hcfec24a_0
  - r-rcolorbrewer=1.1_3=r41h785f33e_0
  - r-rcpp=1.0.8.3=r41h7525677_0
  - r-rcpparmadillo=0.11.0.0.0=r41h43535f1_0
  - r-rcppeigen=0.3.3.9.2=r41h43535f1_0
  - r-rcurl=1.98_1.6=r41hcfec24a_0
  - r-readr=2.1.2=r41h03ef668_0
  - r-readxl=1.4.0=r41hf23e330_0
  - r-registry=0.5_1=r41hc72bb7e_2
  - r-rematch=1.0.1=r41hc72bb7e_1004
  - r-rematch2=2.1.2=r41hc72bb7e_1
  - r-reprex=2.0.1=r41hc72bb7e_0
  - r-reshape2=1.4.4=r41h03ef668_1
  - r-restfulr=0.0.13=r41h73dbb54_2
  - r-rjson=0.2.21=r41h03ef668_0
  - r-rlang=1.0.2=r41h7525677_0
  - r-rmarkdown=2.14=r41hc72bb7e_0
  - r-rngtools=1.5.2=r41hc72bb7e_0
  - r-rprojroot=2.0.3=r41hc72bb7e_0
  - r-rsqlite=2.2.8=r41h03ef668_0
  - r-rstudioapi=0.13=r41hc72bb7e_0
  - r-rttf2pt1=1.3.10=r41hcfec24a_0
  - r-rvest=1.0.2=r41hc72bb7e_0
  - r-sass=0.4.1=r41h7525677_0
  - r-scales=1.2.0=r41hc72bb7e_0
  - r-segmented=1.5_0=r41hc72bb7e_0
  - r-selectr=0.4_2=r41hc72bb7e_1
  - r-seqinr=4.2_8=r41hcfec24a_0
  - r-shape=1.4.6=r41ha770c72_0
  - r-snow=0.4_4=r41hc72bb7e_0
  - r-sp=1.4_7=r41h06615bd_0
  - r-stringi=1.7.6=r41h30a9eb7_2
  - r-stringr=1.4.0=r41hc72bb7e_2
  - r-survival=3.3_1=r41h06615bd_0
  - r-sys=3.4=r41hcfec24a_0
  - r-systemfonts=1.0.4=r41hef9c87a_0
  - r-testthat=3.1.4=r41h7525677_0
  - r-textshaping=0.3.6=r41ha32badf_1
  - r-tibble=3.1.6=r41hcfec24a_0
  - r-tidyr=1.2.0=r41h03ef668_0
  - r-tidyselect=1.1.2=r41hc72bb7e_0
  - r-tidyverse=1.3.1=r41hc72bb7e_0
  - r-tinytex=0.38=r41hc72bb7e_0
  - r-tzdb=0.3.0=r41h7525677_0
  - r-utf8=1.2.2=r41hcfec24a_0
  - r-uuid=1.1_0=r41h06615bd_0
  - r-vctrs=0.4.1=r41h7525677_0
  - r-venndiagram=1.7.3=r41hc72bb7e_0
  - r-vipor=0.4.5=r41hc72bb7e_1003
  - r-viridislite=0.4.0=r41hc72bb7e_0
  - r-visnetwork=2.1.0=r41hc72bb7e_0
  - r-vroom=1.5.7=r41h03ef668_0
  - r-waldo=0.4.0=r41hc72bb7e_0
  - r-withr=2.5.0=r41hc72bb7e_0
  - r-xfun=0.30=r41h7525677_0
  - r-xml=3.99_0.9=r41h06615bd_0
  - r-xml2=1.3.3=r41h7525677_1
  - r-xtable=1.8_4=r41hc72bb7e_3
  - r-yaml=2.3.5=r41h06615bd_0
  - randfold=2.0.1=hec16e2b_4
  - readline=8.1=h46c0cb4_0
  - scikit-learn=1.0.2=py39h4dfa638_0
  - scipy=1.8.0=py39hee8e79c_1
  - sed=4.8=he412f7d_0
  - selenium=4.1.0=pyhd8ed1ab_0
  - setuptools=62.1.0=py39hf3d152e_0
  - six=1.16.0=pyh6c4a22f_0
  - sniffio=1.2.0=py39hf3d152e_3
  - sortedcontainers=2.4.0=pyhd8ed1ab_0
  - soupsieve=2.3.1=pyhd8ed1ab_0
  - sqlite=3.38.2=h4ff8645_0
  - star=2.7.10a=h9ee0642_0
  - sysroot_linux-64=2.12=he073ed8_15
  - tbb=2020.2=h4bd325d_4
  - threadpoolctl=3.1.0=pyh8a188c0_0
  - tk=8.6.12=h27826a3_0
  - tktable=2.10=hb7b940f_3
  - trio=0.20.0=py39hf3d152e_1
  - trio-websocket=0.9.2=pyhd8ed1ab_0
  - tzdata=2022a=h191b570_0
  - urllib3=1.26.9=pyhd8ed1ab_0
  - viennarna=2.5.0=py39pl5321h2add14b_2
  - wheel=0.37.1=pyhd8ed1ab_0
  - wsproto=1.1.0=py39hf3d152e_0
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.0.10=h7f98852_0
  - xorg-libsm=1.2.3=hd9c2040_1000
  - xorg-libx11=1.7.2=h7f98852_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h7f98852_1
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-libxt=1.2.1=h7f98852_2
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.5=h516909a_1
  - zlib=1.2.11=h166bdaf_1014
  - zstd=1.5.2=ha95c52a_0